<project name="OrthoMCLService" basedir=".">

  <!-- oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->
  <!-- oooooooooooooooooooooooooo  Dependencies  oooooooooooooooooooooooooo -->
  <!-- oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->

  <import file="${projectsDir}/EbrcWebSvcCommon/build.xml" />
  <import file="${projectsDir}/OrthoMCLModel/build.xml" />

  <!-- oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->
  <!-- oooooooooooooooooooooooooo  Installation  oooooooooooooooooooooooooo -->
  <!-- oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->

  <target name="OrthoMCLService-Installation" depends="OrthoMCLModel-Installation,
                                                       OrthoMCLService/Service-Installation">
    <ant target="defaultProjectInstall">
      <property name="project" value="OrthoMCLService" />
    </ant>
  </target>

  <target name="OrthoMCLService/Service-Installation">
    <ant target="defaultComponentInstall">
      <property name="project" value="OrthoMCLService" />
      <property name="component" value="Service" />
    </ant>
    <antcall target="createOrthofinderSingularityFile"/>    

  </target>

  <!-- oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->
  <!-- oooooooooooooooooooooooo  Web Installation  oooooooooooooooooooooooo -->
  <!-- oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->

  <target name="OrthoMCLService-WebInstallation" depends="OrthoMCLService-Installation,
                                                          EbrcWebSvcCommon-WebInstallation,
                                                          OrthoMCLService/Service-WebInstallation"/>

  <target name="OrthoMCLService/Service-WebInstallation">
    <ant target="defaultWebComponentInstall">
      <property name="project" value="OrthoMCLService" />
      <property name="component" value="Service" />
    </ant>
  </target>

  <property name="orthofinder_version"  value="1.0.0"/>

  <target name="check-sif-file">
    <condition property="file.missing">
      <not>
        <available file="${targetDir}/lib/sif/orthofinder-${orthofinder_version}.sif"/>
      </not>
    </condition>
  </target>


  <target name="createOrthofinderSingularityFile" depends="check-sif-file" if="file.missing">
    <echo message="Creating OrthoFinder singularity file at ${targetDir}/lib/sif/orthofinder-${orthofinder_version}.sif"/>
    <mkdir dir="${targetDir}/lib/sif"/>
    <exec dir="${targetDir}/lib/sif"
          executable="singularity"
          failonerror="true"
          failifexecutionfails="true">
      <arg line="pull orthofinder-${orthofinder_version}.sif docker://veupathdb/orthofinder:${orthofinder_version}"/>
    </exec>
  </target>

</project>
