#!/usr/bin/perl 

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use CGI qw/:standard/;
use OrthoMCLClient::View::CgiApp::MsaOrthoMCL;

my $cgi = new CGI;

my $app = OrthoMCLClient::View::CgiApp::MsaOrthoMCL->new(ConfigFile => "cryptoModel");

$app->go();
