#!/usr/bin/perl 

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use CGI qw/:standard/;
use OrthoMCLService::Service::CgiApp::MsaOrthoMCL;

my $cgi = new CGI;

my $app = OrthoMCLService::Service::CgiApp::MsaOrthoMCL->new(ConfigFile => "cryptoModel");

$app->go();
